filebeat.prospectors:
  - paths:
      - /apache-logs/access.log
    tags:
      - testenv
      - apache_access
    input_type: log
    document_type: apache_access
    fields_under_root: true

  - paths:
      - /apache-logs/error.log
    tags:
      - testenv
      - apache_error
    input_type: log
    document_type: apache_error
    fields_under_root: true

output.kafka:
  hosts: ["kafka:9092"]
  topic: "log"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
