version: "2"
volumes:
  esdata:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    restart: always
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=test
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - "./esdata:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
    # dns:
    #   - 1111111111111
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    volumes:
      - "./configs/kibana.yml:/usr/share/kibana/config/kibana.yml"
    restart: always
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    # dns:
    #   - 1111111111111
  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    volumes:
      - "./configs/logstash.conf:/config-dir/logstash.conf"
    restart: always
    command: logstash -f /config-dir/logstash.conf
    ports:
      - "9600:9600"
      - "7777:7777"
    links:
      - elasticsearch
    # dns:
    #   - 1111111111111
